CREATE TABLE users (
    user_id VARCHAR(10) PRIMARY KEY,
    name VARCHAR(100),
    age INT,
    gender VARCHAR(10),
    country VARCHAR(50),
    signup_date DATE
);

CREATE TABLE sessions (
    session_id VARCHAR(10) PRIMARY KEY,
    user_id VARCHAR(10),
    session_date DATE,
    duration_min INT,
    device VARCHAR(20),
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE events (
    event_id VARCHAR(10) PRIMARY KEY,
    user_id VARCHAR(10),
    event_date DATE,
    event_type VARCHAR(50),
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);


CREATE TABLE purchases (
    purchase_id VARCHAR(10) PRIMARY KEY,
    user_id VARCHAR(10),
    purchase_date DATE,
    product VARCHAR(100),
    amount DECIMAL(10,2),
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

SELECT * FROM users;

SELECT * FROM sessions;

SELECT * FROM events;

SELECT * FROM purchases;

SELECT COUNT(*) AS total_users
FROM users;

SELECT COUNT(*) AS total_sessions
FROM sessions;

SELECT COUNT(*) AS total_events
FROM events;

SELECT COUNT(*) AS total_purchases
FROM purchases;


-- Q1 How many total users are registered in the app?

SELECT COUNT(*) AS total_users
FROM users;

-- Q2. How many users are there from each country?

SELECT 
    country,
    COUNT(*) AS total_users
FROM users
GROUP BY country
ORDER BY total_users DESC;


-- Q3. How many users are there by gender?

SELECT
    gender,
    COUNT(*) AS total_users
FROM users
GROUP BY gender
ORDER BY total_users DESC;

-- Q4. What is the average age of the users?

SELECT
    ROUND(AVG(age), 2) AS average_age
FROM users;

-- Q5. How many total sessions were recorded?

SELECT
    COUNT(*) AS total_sessions
FROM sessions;

-- Q6. What is the average session duration?

SELECT
    ROUND(AVG(duration_min), 2) AS average_session_duration
FROM sessions;

-- Q7. How many sessions were recorded for each device type?

SELECT
    device,
    COUNT(*) AS total_sessions
FROM sessions
GROUP BY device
ORDER BY total_sessions DESC;

-- Q8. What is the most frequently performed app event?

SELECT
    event_type,
    COUNT(*) AS total_events
FROM events
GROUP BY event_type
ORDER BY total_events DESC
LIMIT 1;

-- Q9. What is the total revenue generated from purchases?

SELECT
    SUM(amount) AS total_revenue
FROM purchases;

-- Q10. What is the average purchase amount?

SELECT
    ROUND(AVG(amount), 2) AS average_purchase_amount
FROM purchases;

-- Q11. Which country generated the highest total purchase revenue?

SELECT
    u.country,
    SUM(p.amount) AS total_revenue
FROM users u
JOIN purchases p
    ON u.user_id = p.user_id
GROUP BY u.country
ORDER BY total_revenue DESC
LIMIT 1;

-- Q12. Which country has the highest number of app users?

SELECT
    country,
    COUNT(*) AS total_users
FROM users
GROUP BY country
ORDER BY total_users DESC
LIMIT 1;

-- Q13. Which device type has the longest average session duration?

SELECT
    device,
    ROUND(AVG(duration_min), 2) AS average_session_duration
FROM sessions
GROUP BY device
ORDER BY average_session_duration DESC
LIMIT 1;

-- Q14. Which country has the highest average purchase amount?

SELECT
    u.country,
    ROUND(AVG(p.amount), 2) AS average_purchase_amount
FROM users u
JOIN purchases p
    ON u.user_id = p.user_id
GROUP BY u.country
ORDER BY average_purchase_amount DESC
LIMIT 1;

-- Q15. Which user has spent the most time using the app?

SELECT
    u.user_id,
    u.name,
    SUM(s.duration_min) AS total_time_spent
FROM users u
JOIN sessions s
    ON u.user_id = s.user_id
GROUP BY u.user_id, u.name
ORDER BY total_time_spent DESC
LIMIT 1;

-- Q16. Which user generated the highest purchase revenue?

SELECT
    u.user_id,
    u.name,
    SUM(p.amount) AS total_spent
FROM users u
JOIN purchases p
    ON u.user_id = p.user_id
GROUP BY u.user_id, u.name
ORDER BY total_spent DESC
LIMIT 1;

-- Q17. Which country has the highest number of app events?

SELECT
    u.country,
    COUNT(e.event_id) AS total_events
FROM users u
JOIN events e
    ON u.user_id = e.user_id
GROUP BY u.country
ORDER BY total_events DESC
LIMIT 1;

-- Q18. What is the total revenue generated by each product?

SELECT
    product,
    SUM(amount) AS total_revenue
FROM purchases
GROUP BY product
ORDER BY total_revenue DESC;

-- Q19. Which country generated the highest revenue from Premium Subscription?

SELECT
    u.country,
    SUM(p.amount) AS total_revenue
FROM users u
JOIN purchases p
    ON u.user_id = p.user_id
WHERE p.product = 'Premium Subscription'
GROUP BY u.country
ORDER BY total_revenue DESC
LIMIT 1;

-- Q20. Which country has the highest average session duration?

SELECT
    u.country,
    ROUND(AVG(s.duration_min), 2) AS average_session_duration
FROM users u
JOIN sessions s
    ON u.user_id = s.user_id
GROUP BY u.country
ORDER BY average_session_duration DESC
LIMIT 1;

-- Q21. Which users have spent more than the average purchase amount?

SELECT
    u.user_id,
    u.name,
    SUM(p.amount) AS total_spent
FROM users u
JOIN purchases p
    ON u.user_id = p.user_id
GROUP BY u.user_id, u.name
HAVING SUM(p.amount) > (
    SELECT AVG(amount)
    FROM purchases
)
ORDER BY total_spent DESC;

SELECT AVG(amount)
FROM purchases


-- Q22. Which users have never made a purchase?

SELECT
    u.user_id,
    u.name
FROM users u
LEFT JOIN purchases p
    ON u.user_id = p.user_id
WHERE p.purchase_id IS NULL
ORDER BY u.user_id;

-- Q23. Which country has the highest total session time?

SELECT
    u.country,
    SUM(s.duration_min) AS total_session_time
FROM users u
JOIN sessions s
    ON u.user_id = s.user_id
GROUP BY u.country
ORDER BY total_session_time DESC
LIMIT 1;

-- Q24. Which app event has the highest number of occurrences in each country?

WITH event_counts AS (
    SELECT
        u.country,
        e.event_type,
        COUNT(*) AS total_events
    FROM users u
    JOIN events e
        ON u.user_id = e.user_id
    GROUP BY u.country, e.event_type
),
ranked_events AS (
    SELECT
        country,
        event_type,
        total_events,
        RANK() OVER (
            PARTITION BY country
            ORDER BY total_events DESC
        ) AS event_rank
    FROM event_counts
)
SELECT
    country,
    event_type,
    total_events
FROM ranked_events
WHERE event_rank = 1
ORDER BY country;

-- Q25. What is the total revenue and average purchase amount for each country?

SELECT
    u.country,
    SUM(p.amount) AS total_revenue,
    ROUND(AVG(p.amount), 2) AS average_purchase_amount
FROM users u
JOIN purchases p
    ON u.user_id = p.user_id
GROUP BY u.country
ORDER BY total_revenue DESC;

-- Q26. Which country has the highest number of active users?

SELECT
    u.country,
    COUNT(DISTINCT s.user_id) AS active_users
FROM users u
JOIN sessions s
    ON u.user_id = s.user_id
GROUP BY u.country
ORDER BY active_users DESC
LIMIT 1;

-- Q27. Which users have the longest average session duration?

SELECT
    u.user_id,
    u.name,
    ROUND(AVG(s.duration_min), 2) AS average_session_duration
FROM users u
JOIN sessions s
    ON u.user_id = s.user_id
GROUP BY u.user_id, u.name
ORDER BY average_session_duration DESC;

-- Q28. Which country has the highest total number of sessions?

SELECT
    u.country,
    COUNT(s.session_id) AS total_sessions
FROM users u
JOIN sessions s
    ON u.user_id = s.user_id
GROUP BY u.country
ORDER BY total_sessions DESC
LIMIT 1;

-- Q29. Which country has the highest total number of purchases?

SELECT
    u.country,
    COUNT(p.purchase_id) AS total_purchases
FROM users u
JOIN purchases p
    ON u.user_id = p.user_id
GROUP BY u.country
ORDER BY total_purchases DESC
LIMIT 1;

-- Q30. Which country has the highest revenue per active user?

WITH country_revenue AS (
    SELECT
        u.country,
        SUM(p.amount) AS total_revenue
    FROM users u
    JOIN purchases p
        ON u.user_id = p.user_id
    GROUP BY u.country
),
country_active_users AS (
    SELECT
        u.country,
        COUNT(DISTINCT s.user_id) AS active_users
    FROM users u
    JOIN sessions s
        ON u.user_id = s.user_id
    GROUP BY u.country
)
SELECT
    r.country,
    r.total_revenue,
    a.active_users,
    ROUND(r.total_revenue / a.active_users, 2) AS revenue_per_active_user
FROM country_revenue r
JOIN country_active_users a
    ON r.country = a.country
ORDER BY revenue_per_active_user DESC
LIMIT 1;
